theme: jekyll-theme-slate


I am relatively new to the world of coding and software, so I'm still learning my way. I’ve always had a good business sense and that comes through in my work. I would personally say my strengths in this industry are in the project management area. I am extremely comfortable in my ability to work with a project from start to finish, not only working with a singular element along the design process.  I am most comfortable with the groundwork element of a project, then developing a launch plan and carrying it out is probably my next strongest skills. 


I have limited experience in working in a team environment in the software field, but I was always good at working with a group in other elements of my life. In my experience solid teamwork is the most important element of software development. Explaining design and function in terms everyone can understand has always been one of my strongest skills, I’ve always had very good communication and leadership skills, I’ve captained pretty much all of the organized sports teams I’ve played on. This is another reason why I find my ability to work in a team environment a strong suit of mine.


I have limited experience with writing algorithms but have been quite successful with the algorithms I have worked with. My only experience in databases is working with MongoDB. I had a few problems early on, but after a few weeks it seemed like a straightforward skill that I was quite comfortable working with. 


Secure coding is something that has been stressed to me in every course I’ve done. I agree with the sentiment that it’s the most important aspect of any project. If you can’t secure your work, there’s no way any client would ever trust you with their information and projects.


ARTIFACTS

The artifacts I’ve chosen for this portfolio are a collection of my most recent completed projects, all these artifacts come from the last 6-8 months. Both of my first two artifacts are written in python as I feel it’s my most comfortable language. Even though I have experience with many of languages, including but not limited to, Java, C, HTML, Assembly, SQL. Artifacts three and four are visual studio projects including both python and C++.  



Artifact 1 is the code for a weather station using a Raspberry pi system with a Grove module. It takes temperature, humidity and light readings ever 30 minutes. If the light threshold is met it activates LED lights and pushes the reading to a json file. That json fil is then used by a web client to publish the weather readings to a webpage. 



Artifact 2 is my work with a MongoDB database. There’s a test file there meant to run the CRUD operation on a database using a test value. Then there’s the actual CRUD file where you can manipulate the database from a text menu. The third file is a search file meant to be used with a stock market database we were given for the class.



Artifact 3 and 4 are very similar projects. Both built for the same class. I included them both to show how I understand the importance of building modular code. I used a large amount of artifact 3 to make artifact 4. 

Artifact 3 is a simple math program that displays a multiplication table based on a user input and then can double that number. 

Artifact 4 is a sales program that takes it’s input from a txt file, formats it, then exports it to a .dat file. The program can show a complete sales list, the amount of a specific item sold, or display a visual histogram of the days sales.
